[0m21:16:52.995164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CA44CFDE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CA44F16550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CA44F15E10>]}


============================== 21:16:53.002504 | 6c3f61e3-6a27-4792-ab03-f9cf2850a871 ==============================
[0m21:16:53.002504 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:16:53.004012 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt docs serve', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:16:53.006039 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\DELL\Desktop\Bigdata_class\Assignment2\Airflow\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:16:53.008028 [debug] [MainThread]: Command `dbt docs serve` failed at 21:16:53.008028 after 0.16 seconds
[0m21:16:53.009028 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CA44F16550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CA44F15C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CA44F15E10>]}
[0m21:16:53.010726 [debug] [MainThread]: Flushing usage events
[0m21:16:53.666090 [debug] [MainThread]: An error was encountered while trying to flush usage events
