[2025-02-14T10:36:33.249+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T10:36:33.269+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_all_snowflake_tables.decide_next_step manual__2025-02-14T10:36:28.034412+00:00 [queued]>
[2025-02-14T10:36:33.281+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_all_snowflake_tables.decide_next_step manual__2025-02-14T10:36:28.034412+00:00 [queued]>
[2025-02-14T10:36:33.281+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T10:36:33.296+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_step> on 2025-02-14 10:36:28.034412+00:00
[2025-02-14T10:36:33.302+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T10:36:33.303+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2025-02-14T10:36:33.304+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'check_all_snowflake_tables', 'decide_next_step', 'manual__2025-02-14T10:36:28.034412+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/snow.py', '--cfg-path', '/tmp/tmp5ui2bghq']
[2025-02-14T10:36:33.307+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask decide_next_step
[2025-02-14T10:36:33.352+0000] {task_command.py:467} INFO - Running <TaskInstance: check_all_snowflake_tables.decide_next_step manual__2025-02-14T10:36:28.034412+00:00 [running]> on host 94016f1f831c
[2025-02-14T10:36:33.413+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_all_snowflake_tables' AIRFLOW_CTX_TASK_ID='decide_next_step' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:36:28.034412+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T10:36:28.034412+00:00'
[2025-02-14T10:36:33.415+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T10:36:33.428+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-14T10:36:33.440+0000] {logging_mixin.py:190} INFO - üîç Debug: Retrieved XCom records: [{'TABLE_COUNT': 0}]
[2025-02-14T10:36:33.440+0000] {logging_mixin.py:190} INFO - Warning: Unexpected XCom format. Proceeding with failure path.
[2025-02-14T10:36:33.441+0000] {python.py:240} INFO - Done. Returned value was: no_required_tables_found
[2025-02-14T10:36:33.442+0000] {branch.py:38} INFO - Branch into no_required_tables_found
[2025-02-14T10:36:33.442+0000] {skipmixin.py:233} INFO - Following branch ('no_required_tables_found',)
[2025-02-14T10:36:33.453+0000] {skipmixin.py:281} INFO - Skipping tasks [('proceed_with_next_task', -1)]
[2025-02-14T10:36:33.479+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T10:36:33.480+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=check_all_snowflake_tables, task_id=decide_next_step, run_id=manual__2025-02-14T10:36:28.034412+00:00, execution_date=20250214T103628, start_date=20250214T103633, end_date=20250214T103633
[2025-02-14T10:36:33.519+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T10:36:33.539+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T10:36:33.541+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
