[2025-02-14T11:30:13.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T11:30:13.053+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_all_snowflake_tables.proceed_with_next_task manual__2025-02-14T11:30:04.316369+00:00 [queued]>
[2025-02-14T11:30:13.070+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_all_snowflake_tables.proceed_with_next_task manual__2025-02-14T11:30:04.316369+00:00 [queued]>
[2025-02-14T11:30:13.073+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T11:30:13.090+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): proceed_with_next_task> on 2025-02-14 11:30:04.316369+00:00
[2025-02-14T11:30:13.097+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T11:30:13.099+0000] {standard_task_runner.py:72} INFO - Started process 191 to run task
[2025-02-14T11:30:13.100+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'check_all_snowflake_tables', 'proceed_with_next_task', 'manual__2025-02-14T11:30:04.316369+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/snow.py', '--cfg-path', '/tmp/tmpyngen52f']
[2025-02-14T11:30:13.105+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask proceed_with_next_task
[2025-02-14T11:30:13.150+0000] {task_command.py:467} INFO - Running <TaskInstance: check_all_snowflake_tables.proceed_with_next_task manual__2025-02-14T11:30:04.316369+00:00 [running]> on host 94016f1f831c
[2025-02-14T11:30:13.221+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_all_snowflake_tables' AIRFLOW_CTX_TASK_ID='proceed_with_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T11:30:04.316369+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T11:30:04.316369+00:00'
[2025-02-14T11:30:13.223+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T11:30:13.235+0000] {logging_mixin.py:190} INFO - âœ… All required tables exist. Proceeding with the next task...
[2025-02-14T11:30:13.236+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T11:30:13.245+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T11:30:13.246+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=check_all_snowflake_tables, task_id=proceed_with_next_task, run_id=manual__2025-02-14T11:30:04.316369+00:00, execution_date=20250214T113004, start_date=20250214T113013, end_date=20250214T113013
[2025-02-14T11:30:13.274+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T11:30:13.293+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T11:30:13.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
